# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'medicine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for medicine
  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Auth'
  pod ‘Firebase/Database’
  pod ‘Firebase/Storage’
  pod 'PickerButton'
  pod 'FSCalendar'
  pod 'CryptoSwift', '~> 1.0'
  pod 'FirebaseUI/Storage'
  pod 'SSZipArchive'
  pod 'ZIPFoundation', '~> 0.9'
  pod 'Zip', '~> 2.1.0'
v
end
